---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-deps:
        patterns:
          - '*'
    commit-message:
      # Prefix all commit messages with "chore(deps): "
      prefix: 'chore(deps): '

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directories:
      - '/'
      - '/packages/*'
    schedule:
      interval: monthly
    groups:
      npm-deps:
        applies-to: security-updates
        dependency-type: production
        patterns:
          - '*'
    commit-message:
      # Prefix all commit messages
      prefix: 'chore(deps): '
    labels:
      - dependabot
      - dependencies
      - vulnerabilites

