---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
    commit-message:
      # Prefix all commit messages
      prefix: 'chore: '
    labels:
      - dependabot
      - dependencies
      - vulnerabilites
    # Allow up to 5 open pull requests
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /examples/create-action
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-batch-proposal
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-monitor
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-proposal
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-relayer-key
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-relayer
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/deploy-contract
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/ethers-signer
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/list-networks
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/relayer-signer-actions
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/simulate-proposal
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/update-action
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/update-monitor
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/update-relayer
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/upgrade-contract
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/action
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/base
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/defender-sdk
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/deploy
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/monitor
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/network
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/notification-channel
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/proposal
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/relay-signer
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/relay
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-forked-network
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/create-private-network
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/custom-ethers-pkg
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/ethers-signer-v5
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/ethers-signer-v6
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/get-usage
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/list-contracts
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/list-proposals
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/relayer-load-balance
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/relayer-signer-auth-v2
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/relayer-web3-provider
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/send-4337-userop/account-kit
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/send-4337-userop/permissionless
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/update-action-env-variables
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/webhook-notification
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/account
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /examples/relayer-call-contract-function
    schedule:
      interval: weekly
