---
# pre-commit install --install-hooks
- id: conventional-pre-commit
  name: Conventional Commit
  entry: conventional-pre-commit
  language: python
  description: Checks commit message for Conventional Commits formatting
  always_run: true
  stages: [commit-msg]
