/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Network } from '@openzeppelin/platform-sdk-base-client';

export interface TenantResponse {
  name?: string;
  networks?: Network[];
  [k: string]: unknown;
}
