---
name: Pre-requisites
description: |
  Setup Pre-requisites

runs:
  using: composite
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
      with:
        persist-credentials: false
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
        cache: 'pnpm'
    - name: Install dependencies
      run: |
        pnpm install-deps
      shell: bash
