---
name: Pre-requisites
description: |
  Setup Pre-requisites

runs:
  using: composite
  steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      with:
        persist-credentials: false
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use node@20
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8  # v4.0.1
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: |
        pnpm install-deps
      shell: bash
