---
name: Pre-requisites
description: |
  Setup Pre-requisites

runs:
  using: composite
  steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
      with:
        persist-credentials: false
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.20.0
        cache: 'pnpm'

    - name: Reconfigure git to use HTTP authentication
      run: |
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/
      shell: bash

    - name: Install dependencies
      if: always()
      run: |
        pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
