name: PR

on:
  push:
    branches:
      - SRE-221-automation
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  start:
    name: Start new release candidate
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: |
            git config user.name 'github-actions'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

  changesets:
    name: Update PR to release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To get all tags
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set release title
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: await require('./scripts/set-changesets-pr-title.js')({ core })
      - name: Create PR
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ env.TITLE }}
          commit: ${{ env.TITLE }}
          body: |
            This is an automated PR for releasing ${{ github.repository }}
            Check [CHANGELOG.md](${{ github.repository }}/CHANGELOG.md)
