name: Test end-to-end

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

env:
  API_KEY: ${{ secrets.E2E_API_KEY }}
  API_SECRET: ${{ secrets.E2E_API_SECRET }}
  DEFENDER_API_URL: $E2E_DEFENDER_API_URL
  DEFENDER_POOL_ID: $E2E_DEFENDER_POOL_ID
  DEFENDER_POOL_CLIENT_ID: $E2E_DEFENDER_POOL_CLIENT_ID

jobs:
  build-test:
    name: Run build & e2e test
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.5.4

    - name: Prepare pre-requisites
      uses: ./.github/actions/prepare

    - name: Build
      run: |
        pnpm nx-build-skip-cache

    - name: Logs env vars
      run: |
        echo "E2E_DEFENDER_API_URL: $E2E_DEFENDER_API_URL" \
        echo "E2E_DEFENDER_POOL_ID: $E2E_DEFENDER_POOL_ID" \
        echo "E2E_DEFENDER_POOL_CLIENT_ID: $E2E_DEFENDER_POOL_CLIENT_ID"

    - name: Test end-to-end
      run: |
        pnpm test:e2e
