---
# This action can be used to draft the next release notes as pull requests are merged into the master.
name: Release Drafter
on:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all


jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@00ce30b0ce8a4d67bccfca59421cdf6c55dd0784 # v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
