---
# This action can be used to draft the next release notes as pull requests are merged into the master.
name: Release Drafter
on:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all


jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2 # v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
