---
# This action can be used to draft the next release notes as pull requests are merged into the master.
name: Release Drafter
on:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all


jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
