name: publish-stable

on:
  workflow_dispatch: {}


# Declare default permissions as read only.
permissions: read-all

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      next_stable_version: ${{ steps.update_version.outputs.next_stable_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v3.6.0
        with:
          ref: master
          token: ${{ secrets.SAI_PAT }}

      - name: Use node@16
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 16.20.0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.SVC_GPG_KEY }}
          passphrase: ${{ secrets.SVC_GPG_PASSPHRASE }}
          git_config_global: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update RC candidate version
        run: |
          yarn versionup:stableminor && ./hack/cross-dependency.sh

      - name: Commit changes
        id: update_version
        run: |
          TAG_NAME=$(node -p "require('./lerna.json').version")
          git add .
          git commit -m "Update version to v$TAG_NAME"
          echo "next_stable_version=v$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag -a ${{ steps.update_version.outputs.next_stable_version }} -m "${{ steps.update_version.outputs.next_stable_version }}"
          git push origin ${{ steps.update_version.outputs.next_stable_version }}
          git push origin master

  create-release:
    name: Create Release
    needs: tag
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.tag.outputs.next_stable_version }}
      prerelease: false
