name: publish-stable

on:
  workflow_dispatch: {}


# Declare default permissions as read only.
permissions: read-all

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      next_stable_version: ${{ steps.update_version.outputs.next_stable_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
        with:
          ref: master
          token: ${{ secrets.SAI_PAT }}

      - name: Use node@20
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8  # v4.0.1
        with:
          node-version: 20

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.SVC_GPG_KEY }}
          passphrase: ${{ secrets.SVC_GPG_PASSPHRASE }}
          git_config_global: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update RC candidate version
        run: |
          yarn versionup:stableminor && ./hack/cross-dependency.sh

      - name: Commit changes
        id: update_version
        run: |
          TAG_NAME=$(node -p "require('./lerna.json').version")
          git add .
          git commit -m "Update version to v$TAG_NAME"
          echo "next_stable_version=v$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag -a ${{ steps.update_version.outputs.next_stable_version }} -m "${{ steps.update_version.outputs.next_stable_version }}"
          git push origin ${{ steps.update_version.outputs.next_stable_version }}
          git push origin master

  create-release:
    name: Create Release
    needs: tag
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.tag.outputs.next_stable_version }}
      prerelease: false
