name: Version Package

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Get github app token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859  # v3.0.0
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.5.4
        with:
          token: ${{ steps.gh-app-token.outputs.token }}

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd
        with:
          gpg_private_key: ${{ secrets.SVC_GPG_KEY }}
          passphrase: ${{ secrets.SVC_GPG_PASSPHRASE }}
          git_config_global: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Release Pull Request
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          setupGitUser: false
          version: pnpm ci:version
          title: "ci: update the version packages"
        env:
          GITHUB_TOKEN: ${{ steps.gh-app-token.outputs.token }}

      - name: Update the lock file
        run: pnpm install --lockfile-only
        shell: bash

      - name: Set up upstream branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/changeset-release/main; then
            git push --set-upstream origin changeset-release/main
          else
            echo "Skipping because the branch changeset-release/main does not exist..."
          fi
        shell: bash

      - name: Commit pnpm-lock.yaml file changes
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        with:
          commit-message: "🤖 chore: Update the pnpm-lock.yaml file"
          title: "chore: 🤖 [Automated PR] Update the pnpm-lock.yaml file"
          committer: svc-gh-is-01 <116854830+svc-gh-is-01@users.noreply.github.com>
          author: svc-gh-is-01 <116854830+svc-gh-is-01@users.noreply.github.com>
          body: |
            This PR updates the pnpm-lock.yaml file
